export default function Terms() {
  return (
    <div style={{ maxWidth: 480, margin: "0 auto", padding: "24px 20px 60px", background: "#060b14", minHeight: "100vh", color: "#94a3b8", fontFamily: "sans-serif" }}>
      <div style={{ color: "#06b6d4", fontSize: 10, letterSpacing: 3, marginBottom: 16 }}>LIFEPATH AI</div>
      <h1 style={{ color: "#fff", fontSize: 22, fontWeight: 800, marginBottom: 8 }}>Terms of Service</h1>
      <div style={{ color: "#475569", fontSize: 11, marginBottom: 32 }}>Last updated: May 2025</div>

      {[
        ["Acceptance", "By using LifePath AI you agree to these terms. If you do not agree, please do not use this service."],
        ["Service Description", "LifePath AI is an AI-powered career and finance guidance tool. We provide general information and suggestions through artificial intelligence. We are not a licensed financial advisor, career counselor, legal advisor, or employment agency."],
        ["AI Disclaimer — IMPORTANT", "All content generated by LifePath AI is for informational and educational purposes only. The AI may make mistakes. Salary figures, market data, company information, and job listings are estimates and may not be accurate or current. Do not make major financial, career, or business decisions based solely on AI-generated content. Always verify information independently and consult qualified professionals."],
        ["Affiliate Links", "LifePath AI includes affiliate links to third-party products and services. We may earn a commission when you click these links or make purchases. This does not affect the price you pay. We only recommend services we believe are genuinely useful."],
        ["User Responsibilities", "You are responsible for how you use the information provided. You must be 13 years or older to use this service. Do not input sensitive financial information like bank account numbers or passwords."],
        ["Limitation of Liability", "LifePath AI and its creators are not liable for any decisions made based on AI-generated content. We are not responsible for accuracy of third-party information, job listings, or salary data. Use this service at your own discretion."],
        ["Changes", "We may update these terms at any time. Continued use of the service means you accept updated terms."],
        ["Contact", "For questions contact: lifepathaiapp@gmail.com"],
      ].map(([title, text], i) => (
        <div key={i} style={{ marginBottom: 24 }}>
          <div style={{ color: "#e2e8f0", fontWeight: 700, fontSize: 14, marginBottom: 8 }}>{title}</div>
          <div style={{ fontSize: 13, lineHeight: 1.7 }}>{text}</div>
        </div>
      ))}

      <a href="/" style={{ display: "block", textAlign: "center", padding: "12px", background: "rgba(6,182,212,0.1)", border: "1px solid rgba(6,182,212,0.3)", borderRadius: 12, color: "#06b6d4", textDecoration: "none", fontSize: 13, fontWeight: 600, marginTop: 20 }}>← Back to LifePath AI</a>
    </div>
  );
}
